### ISSUE TITLE
post错误

### ISSUE THREAD

**Issue by moriweiji** [os7blue/dobby#7]
url:http://127.0.0.1:8082/push
form-data
key:5a1049a7-4b0c-4186-81af-a74c1a5582ac
title:aaa
content:test
返回：json
{
    "code": 0,
    "msg": "invalid character '-' in numeric literal",
    "data": null,
    "count": 0
}

**Comment by os7blue** [comment]
麻烦贴一下 通道方案详情的截图

**Comment by os7blue** [comment]
感谢提醒，过几天有时间会修复一些bug，并且把只允许json的说明添加到管理面板文档中。
